server.port=8080

# H2 (arquivo)
spring.datasource.url=jdbc:h2:file:./data/chronosbr;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

# Log mais limpo
logging.level.org.springframework.security=INFO

# Cookie (dev)
chronosbr.cookie.secure=false
chronosbr.jwt.ttlSeconds=604800

# ============================
# CAPTCHA (reCAPTCHA / hCaptcha)
# ============================
chronosbr.captcha.enabled=false
# permitido: recaptcha,hcaptcha
chronosbr.captcha.allowedProviders=recaptcha,hcaptcha
chronosbr.captcha.defaultProvider=recaptcha

# reCAPTCHA (v3 recomendado)
chronosbr.captcha.recaptcha.secret=6Ldb834sAAAAAO6reYXUebiTMszRhZb1pdcBAp9h
chronosbr.captcha.recaptcha.minScore=0.5

# hCaptcha
chronosbr.captcha.hcaptcha.secret=COLOQUE_SUA_SECRET_HCAPTCHA_AQUI
